Q1)

a)

In [1]:
import numpy as np

# Step a: Create random vector of size 15 with integers from 1 to 20
arr = np.random.randint(1, 21, size=15)

# Step 1: Reshape to 3x5
arr = arr.reshape(3, 5)

# Step 2: Print array shape
print("Array shape:", arr.shape)

# Step 3: Replace max in each row with 0
for i in range(arr.shape[0]):
    row_max_index = arr[i].argmax()  # Index of max element in row
    arr[i, row_max_index] = 0

# Print final array
print("Final array:\n", arr)


Array shape: (3, 5)
Final array:
 [[ 3  0 10 12 12]
 [12  0 14  1  4]
 [11 10  3  0  1]]


b)

In [2]:
import numpy as np

# Create a 2D array of size 4x3 with 4-byte integers (int32)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]], dtype=np.int32)

# Print the array
print("Array:")
print(array)

# Print shape
print("Shape:", array.shape)

# Print type
print("Type:", type(array))

# Print data type
print("Data type:", array.dtype)


Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


c)

In [3]:
import numpy as np

# Define the square array
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("Eigenvalues:")
print(eigenvalues)

print("\nRight Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d)

In [4]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Compute the sum of diagonal elements
diagonal_sum = np.trace(array)

# Print the result
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


e)

In [5]:
import numpy as np

# Original 3x2 array
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

print("Original array (3x2):")
print(original_array)

# Reshape to 2x3
reshaped_array = original_array.reshape(2, 3)

print("\nReshaped array (2x3):")
print(reshaped_array)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
